server:
  port: 8097

spring:
  web:
    resources:
      static-locations: classpath:/static
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
  mvc:
    path-match:
      matching-strategy: ant_path_matcher

transact:
  testException:
    isOn: false